//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertEinsteinHospital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AEH_BDEntities : DbContext
    {
        public AEH_BDEntities()
            : base("name=AEH_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pessoa> PessoaSet { get; set; }
        public virtual DbSet<Medicacao> MedicacaoSet { get; set; }
        public virtual DbSet<Exame> ExameSet { get; set; }
        public virtual DbSet<Sintoma> SintomaSet { get; set; }
        public virtual DbSet<Consulta> ConsultaSet { get; set; }
    }
}
