//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertEinsteinHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sintoma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sintoma()
        {
            this.CompromissoViaAerea = false;
            this.RespiracaoIneficaz = false;
            this.CriancaNaoReativa = false;
            this.Choque = false;
            this.IncapacidadeArticular = false;
            this.TaquicardiaAcentuada = false;
            this.PEFRmb = false;
            this.SAO2mb = false;
            this.AlteracaoConsciencia = false;
            this.PEFRb = false;
            this.SAO2b = false;
            this.HistoriaAsma = false;
            this.Asma = false;
            this.Broncospasmo = false;
            this.ProvavelInfecaoRespiratoria = false;
            this.ProblemaRecente = false;
            this.Outro = false;
        }
    
        public int Id { get; set; }
        public bool CompromissoViaAerea { get; set; }
        public bool RespiracaoIneficaz { get; set; }
        public bool CriancaNaoReativa { get; set; }
        public bool Choque { get; set; }
        public bool IncapacidadeArticular { get; set; }
        public bool TaquicardiaAcentuada { get; set; }
        public bool PEFRmb { get; set; }
        public bool SAO2mb { get; set; }
        public bool AlteracaoConsciencia { get; set; }
        public bool PEFRb { get; set; }
        public bool SAO2b { get; set; }
        public bool HistoriaAsma { get; set; }
        public bool Asma { get; set; }
        public bool Broncospasmo { get; set; }
        public bool ProvavelInfecaoRespiratoria { get; set; }
        public bool ProblemaRecente { get; set; }
        public bool Outro { get; set; }
        public string OutroDescricao { get; set; }
        public string Notas { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Consulta Consulta { get; set; }
    }
}
